### ISSUE TITLE
A question for eaglercraft

### ISSUE THREAD

**Issue by HedgyhogGuy** [lax1dude/origin-blacklist-1.8#2]
1. I have further questions about eaglercraft multiplayer: https://github.com/lax1dude/origin-blacklist-1.8/issues/1#issuecomment-2304728280 
2. are you going to make a more up to date version of eaglercraft (I'm hearing a rumor about 1.12.2 next and want confirmation. I just want to play a version that has the combat update, PLEASE)
3. how did you make Eaglercraft in the first place/what do I need to do to make eaglercraft 
4. sorry about the questions, im new to all this stuff

**Comment by lax1dude** [comment]
This is not the place to ask, and I'm concerned that if I continue to answer questions this way that you and others will open more random bug reports on my repositories to ask me for assistance directly instead of consulting the discord or reddit for answers. Try posting these questions on /r/eaglercraft instead.
